<a href="https://colab.research.google.com/github/EmilSeyfullayev/Work/blob/main/SecurityProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Preprocess

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
def data_preprocesser(data_path: str):
  
  df = pd.read_excel(data_path)
  df = df.drop(['Unnamed: 5',	'Unnamed: 6'], axis=1)
  df = df.iloc[7:].reset_index(drop=True)
  df.columns = ['date', 'time', 'point', 'direction', 'action', 'name']
  df = df[~df['name'].str.contains("Polis turniket")].reset_index(drop=True)

  date_time = []

  for i in range(len(df)):
    date = df['date'][i]
    time = df['time'][i]

    date_time.append(f'{date} {time}')

  df['date_time'] = date_time
  df['date_time'] = pd.to_datetime(df['date_time'])
  df['weekday'] = df['date_time'].apply(lambda x: x.weekday() + 1)

  df['point']  = df['point'].apply(lambda x: x.replace("Turniket Polis 2 (17)", 'main'))

  return df

df = data_preprocesser("/content/drive/MyDrive/Project Security/5.xls")

In [ ]:
names = list(df['name'].unique())
dates = list(df['date'].unique())

In [ ]:
ad2 = []
tarix2 = []
in_datetime = []

for name in names:

  dates = df[df['name'] == name]['date'].unique()

  for date in dates:

    if df[
        (df['name'] == name) &
        (df['date'] == date)
      ]['direction'].iloc[0] == "giriş":

      ad2.append(name)
      tarix2.append(date)

      in_datetime.append(df[
        (df['name'] == name) &
        (df['date'] == date)
      ]['date_time'].iloc[0])


    else:

      ad2.append(name)
      tarix2.append(date)

      in_datetime.append(np.NAN)

In [ ]:
ad = []
tarix = []
out_datetime = []

for name in names:

  dates = df[df['name'] == name]['date'].unique()

  for date in dates:

    if df[
        (df['name'] == name) &
        (df['date'] == date)
      ]['direction'].iloc[-1] == "çıxış ":

      ad.append(name)
      tarix.append(date)

      out_datetime.append(df[
        (df['name'] == name) &
        (df['date'] == date)
      ]['date_time'].iloc[-1])


    else:

      ad.append(name)
      tarix.append(date)

      out_datetime.append(np.NAN)

In [ ]:
print(len(ad))
print(len(tarix))
print(len(ad2))
print(len(tarix2))
print(len(in_datetime))
print(len(out_datetime))

6248
6248
6248
6248
6248
6248

In [ ]:
temp1 = pd.concat([pd.Series(ad2),pd.Series(tarix2),pd.Series(in_datetime)], axis=1)
temp1.columns = ['ad2', 'tarix2', 'giris']
temp2 = pd.concat([pd.Series(ad), pd.Series(tarix), pd.Series(out_datetime)], axis=1)

temp2.columns = ['ad', 'tarix', 'cixis']
temp_merged = pd.concat([temp1, temp2], axis=1)

temp_merged.to_excel('security.xlsx')

for index, value in enumerate(temp_merged['tarix2']):
  if value != temp_merged['tarix2'].iloc[index]:
    print(index) # No problem

In [ ]:
temp_merged

                         ad2      tarix2  ...       tarix               cixis
0     Məlikova Ülkər Müslüm   2021-12-01  ...  2021-12-01 2021-12-01 15:52:09
1     Məlikova Ülkər Müslüm   2021-12-02  ...  2021-12-02 2021-12-02 15:49:28
2     Məlikova Ülkər Müslüm   2021-12-03  ...  2021-12-03 2021-12-03 15:49:39
3     Məlikova Ülkər Müslüm   2021-12-06  ...  2021-12-06 2021-12-06 15:49:37
4     Məlikova Ülkər Müslüm   2021-12-07  ...  2021-12-07 2021-12-07 15:49:12
...                      ...         ...  ...         ...                 ...
6243    Quliyev Vüqar Şirəli  2021-12-28  ...  2021-12-28                 NaT
6244         Kazımova Gövhər  2021-12-28  ...  2021-12-28 2021-12-28 17:32:07
6245         Kazımova Gövhər  2021-12-29  ...  2021-12-29 2021-12-29 17:32:12
6246         Kazımova Gövhər  2021-12-30  ...  2021-12-30 2021-12-30 17:22:47
6247    İsgəndərli Jalə Adil  2021-12-29  ...  2021-12-29 2021-12-29 10:52:04

[6248 rows x 6 columns]

In [ ]:
temp = temp_merged.drop(['ad2', 'tarix2'], axis=1)[['ad', 'tarix', 'giris', 'cixis']]

In [ ]:
checkpoint_1 = df.copy()

In [ ]:
df = temp.copy()

In [ ]:
type(df['giris'].iloc[0]) is pd._libs.tslibs.timestamps.Timestamp

True

In [ ]:
# df['giris_H'] = df['giris'].apply(lambda x: str(x.time()).split(":")[0] if type(x) is pd._libs.tslibs.timestamps.Timestamp else x)
# df['giris_M'] = df['giris'].apply(lambda x: str(x.time()).split(":")[1] if type(x) is pd._libs.tslibs.timestamps.Timestamp else x)
# df['giris_S'] = df['giris'].apply(lambda x: str(x.time()).split(":")[2] if type(x) is pd._libs.tslibs.timestamps.Timestamp else x)

### Preprocess 2

In [ ]:
df

                          ad  ...               cixis
0     Məlikova Ülkər Müslüm   ... 2021-12-01 15:52:09
1     Məlikova Ülkər Müslüm   ... 2021-12-02 15:49:28
2     Məlikova Ülkər Müslüm   ... 2021-12-03 15:49:39
3     Məlikova Ülkər Müslüm   ... 2021-12-06 15:49:37
4     Məlikova Ülkər Müslüm   ... 2021-12-07 15:49:12
...                      ...  ...                 ...
6243    Quliyev Vüqar Şirəli  ...                 NaT
6244         Kazımova Gövhər  ... 2021-12-28 17:32:07
6245         Kazımova Gövhər  ... 2021-12-29 17:32:12
6246         Kazımova Gövhər  ... 2021-12-30 17:22:47
6247    İsgəndərli Jalə Adil  ... 2021-12-29 10:52:04

[6248 rows x 4 columns]

In [ ]:
df['giris_H'] = df['giris'].dt.time

In [ ]:
df['giris_H'] = pd.to_timedelta(df['giris_H'].apply(lambda x: str(x)))

In [ ]:
df['cixis_H'] = df['cixis'].dt.time
df['cixis_H'] = pd.to_timedelta(df['cixis_H'].apply(lambda x: str(x)))

In [ ]:
df[df['cixis'].isna()]

                            ad       tarix  ...         giris_H cixis_H
60    Həsənova Sona Allahverdi  2021-12-08  ... 0 days 06:21:02     NaT
138        Əliyeva Rəna Şirəli  2021-12-01  ... 0 days 06:56:16     NaT
320     Mehdiyev Faiq Cavanşir  2021-12-01  ... 0 days 07:28:02     NaT
321     Mehdiyev Faiq Cavanşir  2021-12-02  ... 0 days 07:31:22     NaT
322     Mehdiyev Faiq Cavanşir  2021-12-03  ... 0 days 07:28:13     NaT
...                        ...         ...  ...             ...     ...
6229      Məmmədov Natiq Mirzə  2021-12-28  ... 0 days 09:19:29     NaT
6230      Məmmədov Natiq Mirzə  2021-12-29  ... 0 days 09:26:57     NaT
6231      Məmmədov Natiq Mirzə  2021-12-30  ... 0 days 09:10:38     NaT
6232      Vüqar Qurbanov Namaz  2021-12-22  ... 0 days 14:07:02     NaT
6243      Quliyev Vüqar Şirəli  2021-12-28  ... 0 days 10:21:04     NaT

[476 rows x 6 columns]

In [ ]:
names_one_cixis_or_giris_is_na = []

for name in set(
    list(
        df[
           df['cixis'].isna()
        ]['ad']
    )
):

  if len(df[df['ad'] == name]) == len(df[(df['ad'] == name) & (df['cixis'].isna())]):

    names_one_cixis_or_giris_is_na.append(name)

In [ ]:
names_one_cixis_or_giris_is_na

['Hünbətov Emil Eyvaz',
 'Quliyev Vüqar Şirəli',
 'Elxan Əsgərzadə',
 'Baxışov Samir Rəşadət',
 'Vüqar Qurbanov Namaz']

In [ ]:
counts_df = df.groupby('ad').count()[['tarix', 'giris', 'cixis']]#.reset_index(drop=True)

In [ ]:
counts_df = counts_df.reset_index()

In [ ]:
counts_df['girislerin_az_sayi'] = counts_df['tarix'] - counts_df['giris']
counts_df['cixislarin_az_sayi'] = counts_df['tarix'] - counts_df['cixis']
#counts_df = counts_df.drop(['girislerin_az_sayi', 'cixislarin_az_sayi'], axis=1)
counts_df

                             ad  tarix  ...  girislerin_az_sayi  cixislarin_az_sayi
0     Bayramov Əflatun Şəmistan     18  ...                   1                   2
1      Abasova Nəzakət Mirsahib     25  ...                   0                   0
2         Abbasov Telman Məmməd      8  ...                   0                   0
3            Abbasova Güləndam      23  ...                   0                   0
4               Abbasova Əfsanə     12  ...                   0                   8
..                          ...    ...  ...                 ...                 ...
329            Əzim Elmin Oktay     19  ...                   0                   1
330          Əzimov İlqar İlham     18  ...                   0                  17
331               Əzizli Ruslan     21  ...                   0                   0
332               Əzizli Yeganə     21  ...                   0                   0
333          Əzizov Orxan Vasif     23  ...                   0                   0

[334 rows x 6 columns]

In [ ]:
counts_df.sort_values('girislerin_az_sayi', ascending=False)[counts_df['girislerin_az_sayi']>3]

In [ ]:
adlar_girislerin_az_olma_sayi_3_den_cox = list(counts_df.sort_values('girislerin_az_sayi', ascending=False)[counts_df['girislerin_az_sayi']>3]['ad'])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

In [ ]:
adlar_girislerin_az_olma_sayi_3_den_cox

['Əliyev İlkin Zahid',
 'Kərimli Elşən Aydın',
 'Satiyev İlqar',
 'Qədirzadə Tural Murad',
 'Kərimov Aydın Mikayıl',
 'Əsgərova Aynur Elxan ',
 'Həsənov Səlim Rza',
 'Quliyeva Sona Elman',
 'Şirinov Kənan Rasim']

In [ ]:
adlar_cixislarin_az_olma_sayi_3_den_cox = list(counts_df.sort_values('cixislarin_az_sayi', ascending=False)[counts_df['cixislarin_az_sayi']>3]['ad'])
adlar_cixislarin_az_olma_sayi_3_den_cox

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

['Qurbanov Natiq Cəlal (muzey)',
 'Mühafizə',
 'Əliyev Fərid İsgəndər',
 'Salmanova Aydan Mətləb ',
 'Mehdiyev Faiq Cavanşir',
 'Əzimov İlqar İlham',
 'İbadov Elnur Adəm',
 'Rüstəmzadə Səbinə Aydın',
 'Müsəvi Türkan Nizami',
 'Şirinov Kənan Rasim',
 'Şərifli Kamran Mehman',
 'Quliyev Nihad Qüdrət',
 'Mirzəzadə Nəzakət Qabil',
 'Əliyeva İlahə Mirsə-Əli',
 'Səlimov Aslan Yusif',
 'Cəlilova Aysel Rövşən',
 'Həsənova Vəfa Səlim',
 'Əbilov Elyar Sultan',
 'Kərimov Aydın Mikayıl',
 'Kərimli Elşən Aydın',
 'Qədirzadə Tural Murad',
 'Abbasova Əfsanə',
 'Hacıyev Fuad Allahverdi ',
 'Yusifli Əsmər Nəriman',
 'Həsənova Günel Pənah',
 'Sərdarov Aqil Yaqub',
 'Ağayev Murad Vahid',
 'Həsənov Səlim Rza',
 'Əliyev İlkin Zahid',
 'Hacıyev Natiq Rzaqulu',
 'Məmmədov Natiq Mirzə',
 'Misirli Misir Yusir',
 'Satiyev İlqar',
 'Mürşüdova İradə İsbəndiyar',
 'Aslanov Rasim Rafiq',
 'Hünbətov Emil Eyvaz',
 'Hüseynli Həbib Şahin']

In [ ]:
problemli_adlar = [*names_one_cixis_or_giris_is_na,
                   *adlar_girislerin_az_olma_sayi_3_den_cox, 
                   *adlar_cixislarin_az_olma_sayi_3_den_cox]

In [ ]:
pd.DataFrame(problemli_adlar).to_excel("Problemli_adlar.xlsx")

In [ ]:
df_problemli_adlar  = df[df['ad'].isin(problemli_adlar)].reset_index(drop=True)
df_problemsiz_adlar = df[~df['ad'].isin(problemli_adlar)].reset_index(drop=True)

In [ ]:
df_problemli_adlar.to_excel("Problemli_Kart_İstifadecileri.xlsx")

In [ ]:
df_problemli_adlar.groupby('ad').count().sort_values(by='tarix', ascending=False).to_excel("Problemli_adlar_say.xlsx")

In [ ]:
df.isna().sum()

ad           0
tarix        0
giris      116
cixis      476
giris_H    116
cixis_H    476
dtype: int64

In [ ]:
temp = df_problemsiz_adlar.groupby("ad").transform(lambda x: x.fillna(x.mean()))#.isna().sum()
temp = pd.concat([df_problemsiz_adlar['ad'], temp], axis=1)
temp

                          ad  ...         cixis_H
0     Məlikova Ülkər Müslüm   ... 0 days 15:52:09
1     Məlikova Ülkər Müslüm   ... 0 days 15:49:28
2     Məlikova Ülkər Müslüm   ... 0 days 15:49:39
3     Məlikova Ülkər Müslüm   ... 0 days 15:49:37
4     Məlikova Ülkər Müslüm   ... 0 days 15:49:12
...                      ...  ...             ...
5573  Bayramova Gülər Rövşən  ... 0 days 19:57:47
5574         Kazımova Gövhər  ... 0 days 17:32:07
5575         Kazımova Gövhər  ... 0 days 17:32:12
5576         Kazımova Gövhər  ... 0 days 17:22:47
5577    İsgəndərli Jalə Adil  ... 0 days 10:52:04

[5578 rows x 5 columns]

In [ ]:
temp.isna().sum()

ad         0
giris      0
cixis      0
giris_H    0
cixis_H    0
dtype: int64

In [ ]:
temp['difference'] = temp['cixis_H'] - temp['giris_H']

In [ ]:
temp

                          ad  ...             difference
0     Məlikova Ülkər Müslüm   ...        0 days 09:44:14
1     Məlikova Ülkər Müslüm   ...        0 days 07:25:03
2     Məlikova Ülkər Müslüm   ...        0 days 08:38:22
3     Məlikova Ülkər Müslüm   ...        0 days 08:34:33
4     Məlikova Ülkər Müslüm   ...        0 days 08:20:20
...                      ...  ...                    ...
5573  Bayramova Gülər Rövşən  ...        0 days 10:35:11
5574         Kazımova Gövhər  ... 0 days 08:05:51.500000
5575         Kazımova Gövhər  ...        0 days 08:07:56
5576         Kazımova Gövhər  ...        0 days 07:54:32
5577    İsgəndərli Jalə Adil  ...        0 days 00:21:22

[5578 rows x 6 columns]

In [ ]:
temp2 = temp.groupby('ad').sum('difference').sort_values(by='difference', ascending=False).reset_index()
temp2

                              ad  ...             difference
0       Məhərrəmova Şeyda Məmməd  ...       12 days 23:24:13
1          Xəlilova Səbinə Hakim  ...       12 days 12:04:51
2    Nəcəfova Rəhilə Allahverdi   ...       10 days 07:18:43
3       Abasova Nəzakət Mirsahib  ...       10 days 04:52:59
4       Cəfərova Qərənfil Məmməd  ...        9 days 23:26:01
..                           ...  ...                    ...
286        Tağıyeva Sitarə Sabir  ...        0 days 00:37:15
287         İsgəndərli Jalə Adil  ...        0 days 00:21:22
288          Əlizadə İlkin Cəmil  ...        0 days 00:19:32
289     Zalov Zaur (Abşeron RSL)  ... 0 days 00:10:19.500000
290       Ələkbərov Malik Mürsəl  ...      -1 days +22:19:52

[291 rows x 4 columns]

In [ ]:
temp2['difference_hours'] = temp2['difference'].apply(lambda x: x/np.timedelta64(1, 'h'))

In [ ]:
temp2['diffrence_percent'] = round((temp2['difference_hours']/197)*100, 2)

In [ ]:
temp2.to_excel('saatlar.xlsx')

In [ ]:
temp3 = temp.groupby('ad').count().reset_index()

In [ ]:
temp2.shape

(291, 6)

In [ ]:
temp3.shape

(291, 6)

In [ ]:
sorter = list(temp2['ad'])

In [ ]:
temp3['ad'] = temp3['ad'].astype("category")

In [ ]:
temp3['ad'].cat.set_categories(sorter, inplace = True)

In [ ]:
temp3 = temp3.sort_values('ad').reset_index()

In [ ]:
pd.concat([temp2, temp3], axis=1).to_excel("final.xlsx")

In [ ]:
temp[temp['ad'] == 'Talıbzadə Ədalət Yusif']

                          ad  ...             difference
2164  Talıbzadə Ədalət Yusif  ...        0 days 09:05:28
2165  Talıbzadə Ədalət Yusif  ...        0 days 07:56:47
2166  Talıbzadə Ədalət Yusif  ...        0 days 10:10:06
2167  Talıbzadə Ədalət Yusif  ...        0 days 04:49:09
2168  Talıbzadə Ədalət Yusif  ...        0 days 08:36:26
2169  Talıbzadə Ədalət Yusif  ...        0 days 13:43:24
2170  Talıbzadə Ədalət Yusif  ...        0 days 11:28:10
2171  Talıbzadə Ədalət Yusif  ...        0 days 08:06:47
2172  Talıbzadə Ədalət Yusif  ...        0 days 09:04:19
2173  Talıbzadə Ədalət Yusif  ...        0 days 10:15:39
2174  Talıbzadə Ədalət Yusif  ...        0 days 09:15:31
2175  Talıbzadə Ədalət Yusif  ...        0 days 08:16:39
2176  Talıbzadə Ədalət Yusif  ...        0 days 10:30:20
2177  Talıbzadə Ədalət Yusif  ...        0 days 10:28:13
2178  Talıbzadə Ədalət Yusif  ...        0 days 10:25:09
2179  Talıbzadə Ədalət Yusif  ...        0 days 08:56:06
2180  Talıbzadə Ədalət Yusif  ...        0 days 10:09:11
2181  Talıbzadə Ədalət Yusif  ...        0 days 09:34:35
2182  Talıbzadə Ədalət Yusif  ...        0 days 09:48:12
2183  Talıbzadə Ədalət Yusif  ...        0 days 10:03:14
2184  Talıbzadə Ədalət Yusif  ...        0 days 05:44:18
2185  Talıbzadə Ədalət Yusif  ...        0 days 09:48:15
2186  Talıbzadə Ədalət Yusif  ...        0 days 09:55:44
2187  Talıbzadə Ədalət Yusif  ... 0 days 09:15:38.160000
2188  Talıbzadə Ədalət Yusif  ...        0 days 08:49:06
2189  Talıbzadə Ədalət Yusif  ...        0 days 01:30:05

[26 rows x 6 columns]

In [ ]:
temp.to_excel("Etrafli.xlsx")

In [ ]:
df['cixis_H'].iloc[0]

Timedelta('0 days 15:52:09')

In [ ]:
df['giris_H'].iloc[0]

Timedelta('0 days 06:07:55')

In [ ]:
df_problemsiz_adlar.iloc[5567]

ad         Vüqar Qurbanov Namaz
tarix                2021-12-22
giris       2021-12-22 14:07:02
cixis                       NaT
giris_H         0 days 14:07:02
cixis_H                     NaT
Name: 5567, dtype: object

In [ ]:
df[df['ad'] == 'Quliyev Vüqar Şirəli']

                        ad       tarix  ...         giris_H cixis_H
6243  Quliyev Vüqar Şirəli  2021-12-28  ... 0 days 10:21:04     NaT

[1 rows x 6 columns]

In [ ]:
df[df['ad'] == 'Vüqar Qurbanov Namaz']

                        ad       tarix  ...         giris_H cixis_H
6232  Vüqar Qurbanov Namaz  2021-12-22  ... 0 days 14:07:02     NaT

[1 rows x 6 columns]

In [ ]:
counts_df.sort_values('cixislarin_az_sayi', ascending=False)[counts_df['cixislarin_az_sayi']>3]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

                               ad  ...  cixislarin_az_sayi
200  Qurbanov Natiq Cəlal (muzey)  ...                  22
135                      Mühafizə  ...                  22
301         Əliyev Fərid İsgəndər  ...                  22
230       Salmanova Aydan Mətləb   ...                  20
115        Mehdiyev Faiq Cavanşir  ...                  20
330            Əzimov İlqar İlham  ...                  17
274             İbadov Elnur Adəm  ...                  16
216       Rüstəmzadə Səbinə Aydın  ...                  15
139          Müsəvi Türkan Nizami  ...                  15
289           Şirinov Kənan Rasim  ...                  13
294         Şərifli Kamran Mehman  ...                  12
192          Quliyev Nihad Qüdrət  ...                  12
121       Mirzəzadə Nəzakət Qabil  ...                  12
316       Əliyeva İlahə Mirsə-Əli  ...                  11
244           Səlimov Aslan Yusif  ...                  10
56          Cəlilova Aysel Rövşən  ...                   9
101           Həsənova Vəfa Səlim  ...                   9
295           Əbilov Elyar Sultan  ...                   9
110         Kərimov Aydın Mikayıl  ...                   8
109           Kərimli Elşən Aydın  ...                   8
206         Qədirzadə Tural Murad  ...                   8
4                 Abbasova Əfsanə  ...                   8
69       Hacıyev Fuad Allahverdi   ...                   7
262         Yusifli Əsmər Nəriman  ...                   7
98           Həsənova Günel Pənah  ...                   7
249           Sərdarov Aqil Yaqub  ...                   7
30             Ağayev Murad Vahid  ...                   7
94              Həsənov Səlim Rza  ...                   7
303            Əliyev İlkin Zahid  ...                   7
70          Hacıyev Natiq Rzaqulu  ...                   6
146          Məmmədov Natiq Mirzə  ...                   6
123           Misirli Misir Yusir  ...                   5
231                 Satiyev İlqar  ...                   4
138    Mürşüdova İradə İsbəndiyar  ...                   4
22            Aslanov Rasim Rafiq  ...                   4
80            Hünbətov Emil Eyvaz  ...                   4
81           Hüseynli Həbib Şahin  ...                   4

[37 rows x 6 columns]

In [ ]:
temp = counts_df['tarix'].value_counts().reset_index()

In [ ]:
temp[temp['index'] < 15]['tarix'].sum()

68

In [ ]:
counts_df.sort_values('tarix', ascending=False).head(60)

                                ad  ...  cixislarin_az_sayi
54        Cəfərova Qərənfil Məmməd  ...                   0
310           Əliyeva Reyhan Şamil  ...                   0
85     Hüseynova Minəxanım Abdulla  ...                   0
204            Qədimova Samirə Əli  ...                   0
180                Paşazadə Toğrul  ...                   0
42          Bayramzadə Emin Salman  ...                   0
244            Səlimov Aslan Yusif  ...                  10
251         Talıbzadə Ədalət Yusif  ...                   1
164         Namazova Gülnar Məcnun  ...                   0
37         Bayramov Cahangir Tofiq  ...                   3
260          Xəlilova Səbinə Hakim  ...                   0
141       Məhərrəmova Şeyda Məmməd  ...                   0
257            Vətəni Mahirə Əhməd  ...                   0
90         Hüseynova Ülviyyə Hafis  ...                   1
127            Musayev Tural Vüqar  ...                   0
237        Sultanlı Saqibət Pərviz  ...                   0
1         Abasova Nəzakət Mirsahib  ...                   0
71          Hacıyeva Cəmilə Telman  ...                   0
190       Qazıyeva Saida Seyfəddin  ...                   1
70           Hacıyev Natiq Rzaqulu  ...                   6
53           Cəfərova Günel Səyad   ...                   0
106           Kazımov Rahib Zinhar  ...                   0
186            Qanbay Maqsud Murad  ...                   2
287         Şafahatzadə Fuad Əşrəf  ...                   0
309                 Əliyeva Nuridə  ...                   0
118           Mirzəli Vüsalə İlyas  ...                   0
119      Mirzəyeva Nigar Fəxrəddin  ...                   1
142         Məlikova Ülkər Müslüm   ...                   0
175    Nəcəfova Rəhilə Allahverdi   ...                   0
200   Qurbanov Natiq Cəlal (muzey)  ...                  22
179               Orxan Mahir oğlu  ...                   0
277  İbrahimova Mələkxanım İnqilab  ...                   0
188                 Qasımlı Qasım   ...                   0
267       Zamanova Sevinc Nuhiddin  ...                   0
195         Quliyeva Aynurə Şahlar  ...                   0
73           Hacıyeva Nigar Üzeyir  ...                   0
262          Yusifli Əsmər Nəriman  ...                   7
78             Hilalova Rəna Vaqif  ...                   0
243    Səfərəliyeva Nərgiz İsmayıl  ...                   0
82        Hüseynov Hikmət Cəbrayıl  ...                   3
145          Məmmədov Bayram Ənvər  ...                   0
135                       Mühafizə  ...                  22
220            Sadıqova Arzu Əbil   ...                   0
92      Həsənli Tamilla Səlahəddin  ...                   0
115         Mehdiyev Faiq Cavanşir  ...                  20
114       Mahmudova Mahirə Hacıağa  ...                   0
333             Əzizov Orxan Vasif  ...                   0
26             Axundova Ebru Nabil  ...                   0
318          Əliyeva Şəlalə Çingiz  ...                   2
3               Abbasova Güləndam   ...                   0
298        Əhmədova Cəmilə Ağamusa  ...                   0
301          Əliyev Fərid İsgəndər  ...                  22
14            Abışova Nuranə Elçin  ...                   0
138     Mürşüdova İradə İsbəndiyar  ...                   4
137        Mürşüdova Bürhanə Qədəm  ...                   2
136          Mürsəlli Səmra Nizami  ...                   0
15     Allahverdiyev Fuad Qələndər  ...                   1
217       Rəfiyeva Mələkxanım Azad  ...                   1
133      Mustafayeva Nailə Xanbaba  ...                   0
132       Mustafayeva Kəmalə Vəkil  ...                   0

[60 rows x 6 columns]

In [ ]:
df_na = df[
   (df['giris_H'].isna()) |
   (df['cixis_H'].isna())
]

In [ ]:
dovrun_baslangic = df.iloc[2,3]
dovrun_baslangic

'01.12.2021 00:00:00'

In [ ]:
dovrun_bitmesi = df.iloc[3,3]
dovrun_bitmesi

'01.01.2022 00:00:00'

In [ ]:
df = df.drop(['Unnamed: 5',	'Unnamed: 6'], axis=1)

In [ ]:
df = df.iloc[7:].reset_index(drop=True)

In [ ]:
df

      Sistemin hadisələr qeyd olunan jurnalı.  ...      Unnamed: 7
0                                  2021-12-01  ...  Polis turniket
1                                  2021-12-01  ...  Polis turniket
2                                  2021-12-01  ...  Polis turniket
3                                  2021-12-01  ...  Polis turniket
4                                  2021-12-01  ...  Polis turniket
...                                       ...  ...             ...
20275                              2021-12-31  ...  Polis turniket
20276                              2021-12-31  ...  Polis turniket
20277                              2021-12-31  ...  Polis turniket
20278                              2021-12-31  ...  Polis turniket
20279                              2021-12-31  ...  Polis turniket

[20280 rows x 6 columns]

In [ ]:
df.columns = ['date', 'time', 'point', 'direction', 'action', 'name']

In [ ]:
df

             date      time  ...                    action            name
0      2021-12-01  01:20:54  ...  Keçid qeydə alınmışdır.   Polis turniket
1      2021-12-01  01:22:20  ...  Keçid qeydə alınmışdır.   Polis turniket
2      2021-12-01  01:23:33  ...  Keçid qeydə alınmışdır.   Polis turniket
3      2021-12-01  01:24:29  ...  Keçid qeydə alınmışdır.   Polis turniket
4      2021-12-01  06:07:25  ...  Keçid qeydə alınmışdır.   Polis turniket
...           ...       ...  ...                       ...             ...
20275  2021-12-31  20:33:25  ...  Keçid qeydə alınmışdır.   Polis turniket
20276  2021-12-31  20:34:19  ...  Keçid qeydə alınmışdır.   Polis turniket
20277  2021-12-31  20:35:01  ...  Keçid qeydə alınmışdır.   Polis turniket
20278  2021-12-31  20:56:34  ...  Keçid qeydə alınmışdır.   Polis turniket
20279  2021-12-31  20:57:11  ...  Keçid qeydə alınmışdır.   Polis turniket

[20280 rows x 6 columns]

In [ ]:
df = df[~df['name'].str.contains("Polis turniket")].reset_index(drop=True)

In [ ]:
df['name'].value_counts()

Məmmədzadə Rəşad Əli         203
Mahmudov Həsən Hüsən         199
Məmmədəliyev İlkin Adil      172
Seyfullayev Samir Mübariz    161
Səlimov Aslan Yusif          150
                            ...
Həşimov Həşim Eldar            2
Məmmədli Vüqar Ədalət          2
Süleymanov Elman Məhəmməd      2
Quliyev Vüqar Şirəli           1
Baxışov Samir Rəşadət          1
Name: name, Length: 334, dtype: int64

In [ ]:
df['point'].value_counts()

Turniket Polis 2 (17)        14487
Zirzemi (lift) (22)           1506
Turniket MRL (19)             1367
Turniket Polis 1 (16)          892
Turniket AQTI 1 (20)           453
Zirzemi (arxa giris) (23)      363
Turniket AQTI 2 (21)           196
Name: point, dtype: int64

In [ ]:
df['name'].value_counts()

Məmmədzadə Rəşad Əli         203
Mahmudov Həsən Hüsən         199
Məmmədəliyev İlkin Adil      172
Seyfullayev Samir Mübariz    161
Səlimov Aslan Yusif          150
                            ...
Həşimov Həşim Eldar            2
Məmmədli Vüqar Ədalət          2
Süleymanov Elman Məhəmməd      2
Quliyev Vüqar Şirəli           1
Baxışov Samir Rəşadət          1
Name: name, Length: 334, dtype: int64

In [ ]:
df[df['point'] == 'Turniket Polis 2 (17)']['name'].value_counts()

Səfərli Sərxan                 97
Hüseynova Minəxanım Abdulla    97
Seyfullayev Emil Məzahim       94
Musayev Tural Vüqar            92
Talıbzadə Ədalət Yusif         88
                               ..
Rüstəmzadə Səbinə Aydın         1
Məmmədov Natiq Mirzə            1
Əliyev Fərid İsgəndər           1
Hünbətov Emil Eyvaz             1
Həsənova Günel Pənah            1
Name: name, Length: 327, dtype: int64

In [ ]:
names = df['name'].unique()

In [ ]:
dates = df['date'].unique()

In [ ]:
date_time = []

for i in range(len(df)):
   date = df['date'][i]
   time = df['time'][i]

   date_time.append(f'{date} {time}')

df['date_time'] = date_time
df['date_time'] = pd.to_datetime(df['date_time'])

In [ ]:
df['date_time'] = date_time

In [ ]:
df['date_time'] = pd.to_datetime(df['date_time'])

In [ ]:
df['date_time']

0       2021-12-01 06:07:55
1       2021-12-01 06:11:04
2       2021-12-01 06:23:22
3       2021-12-01 06:23:25
4       2021-12-01 06:23:28
                ...
19259   2021-12-31 13:17:25
19260   2021-12-31 13:19:02
19261   2021-12-31 13:25:04
19262   2021-12-31 15:15:04
19263   2021-12-31 16:23:32
Name: date_time, Length: 19264, dtype: datetime64[ns]

In [ ]:
df

             date      time  ...                      name           date_time
0      2021-12-01  06:07:55  ...    Məlikova Ülkər Müslüm  2021-12-01 06:07:55
1      2021-12-01  06:11:04  ...   Sadıqzadə Həlimə Qaraş  2021-12-01 06:11:04
2      2021-12-01  06:23:22  ...  Mahmudova Mahirə Hacıağa 2021-12-01 06:23:22
3      2021-12-01  06:23:25  ...  Həsənova Sona Allahverdi 2021-12-01 06:23:25
4      2021-12-01  06:23:28  ...     Zeynalova Pərvanə Əli 2021-12-01 06:23:28
...           ...       ...  ...                       ...                 ...
19259  2021-12-31  13:17:25  ...   Bayramov Cahangir Tofiq 2021-12-31 13:17:25
19260  2021-12-31  13:19:02  ...            Zalova Gülnarə 2021-12-31 13:19:02
19261  2021-12-31  13:25:04  ...   Bayramov Cahangir Tofiq 2021-12-31 13:25:04
19262  2021-12-31  15:15:04  ...      Əliyeva Fatimə Əhməd 2021-12-31 15:15:04
19263  2021-12-31  16:23:32  ...       Səlimov Aslan Yusif 2021-12-31 16:23:32

[19264 rows x 7 columns]

In [ ]:
ulker = df[df['name'] == names[0]]

In [ ]:
ulker[ulker['date'] == dates[7]]

            date      time  ...                    name           date_time
4589  2021-12-08  06:35:33  ...  Məlikova Ülkər Müslüm  2021-12-08 06:35:33
4590  2021-12-08  06:38:05  ...  Məlikova Ülkər Müslüm  2021-12-08 06:38:05
4591  2021-12-08  06:38:50  ...  Məlikova Ülkər Müslüm  2021-12-08 06:38:50
4945  2021-12-08  12:56:03  ...  Məlikova Ülkər Müslüm  2021-12-08 12:56:03
5022  2021-12-08  13:37:53  ...  Məlikova Ülkər Müslüm  2021-12-08 13:37:53
5101  2021-12-08  15:48:39  ...  Məlikova Ülkər Müslüm  2021-12-08 15:48:39

[6 rows x 7 columns]

In [ ]:
ulker[
      (ulker['date'] == dates[7]) &
      (ulker['direction'] == 'giriş')
]['date_time']

4589   2021-12-08 06:35:33
4591   2021-12-08 06:38:50
5022   2021-12-08 13:37:53
Name: date_time, dtype: datetime64[ns]

In [ ]:
ulker[
      (ulker['date'] == dates[7]) &
      (ulker['direction'] == 'çıxış ')
]['date_time'].reset_index(drop=True).iloc[-1]

Timestamp('2021-12-08 15:48:39')

In [ ]:
ulker[
      (ulker['date'] == dates[7]) &
      (ulker['direction'] == 'çıxış ')
]['date_time'].reset_index(drop=True).iloc[-1] - ulker[
      (ulker['date'] == dates[7]) &
      (ulker['direction'] == 'giriş')
]['date_time'].reset_index(drop=True).iloc[1]

Timedelta('0 days 09:09:49')

### Is for each day number of giris  == cixis?

In [ ]:
dates_ulker = ulker['date'].unique()

In [ ]:
for i in dates_ulker:

  temp = ulker[ulker['date'] == i] 

  if temp['direction'].value_counts()[0]  != temp['direction'].value_counts()[1]:
    pass

  elif temp['direction'].value_counts()[0]  == temp['direction'].value_counts()[1]:

    a = temp['direction'].value_counts().index[0]
    b = temp['direction'].value_counts()[0]
    c = temp['direction'].value_counts().index[1]
    d = temp['direction'].value_counts()[1]

    print(f'{i} tarix üçün {a} sayı:{b} və {c} sayı: {d}')

2021-12-01 tarix üçün çıxış  sayı:1 və giriş sayı: 1
2021-12-02 tarix üçün çıxış  sayı:2 və giriş sayı: 2
2021-12-03 tarix üçün çıxış  sayı:2 və giriş sayı: 2
2021-12-06 tarix üçün çıxış  sayı:1 və giriş sayı: 1
2021-12-07 tarix üçün çıxış  sayı:2 və giriş sayı: 2
2021-12-08 tarix üçün çıxış  sayı:3 və giriş sayı: 3
2021-12-09 tarix üçün çıxış  sayı:1 və giriş sayı: 1
2021-12-10 tarix üçün çıxış  sayı:1 və giriş sayı: 1
2021-12-11 tarix üçün çıxış  sayı:1 və giriş sayı: 1
2021-12-13 tarix üçün çıxış  sayı:1 və giriş sayı: 1
2021-12-15 tarix üçün çıxış  sayı:1 və giriş sayı: 1
2021-12-16 tarix üçün çıxış  sayı:1 və giriş sayı: 1
2021-12-17 tarix üçün çıxış  sayı:2 və giriş sayı: 2
2021-12-18 tarix üçün çıxış  sayı:1 və giriş sayı: 1
2021-12-20 tarix üçün çıxış  sayı:2 və giriş sayı: 2
2021-12-21 tarix üçün çıxış  sayı:2 və giriş sayı: 2
2021-12-22 tarix üçün çıxış  sayı:2 və giriş sayı: 2
2021-12-23 tarix üçün çıxış  sayı:1 və giriş sayı: 1
2021-12-24 tarix üçün çıxış  sayı:1 və giriş sayı: 1
2021-12-25 tarix üçün çıxış  sayı:1 və giriş sayı: 1
2021-12-27 tarix üçün çıxış  sayı:1 və giriş sayı: 1
2021-12-28 tarix üçün çıxış  sayı:1 və giriş sayı: 1
2021-12-29 tarix üçün çıxış  sayı:1 və giriş sayı: 1
2021-12-30 tarix üçün çıxış  sayı:1 və giriş sayı: 1

In [ ]:
df = data_preprocesser("/content/drive/MyDrive/Project Security/5.xls")

In [ ]:
df['point'].value_counts()

Turniket Polis 2 (17)        14487
Zirzemi (lift) (22)           1506
Turniket MRL (19)             1367
Turniket Polis 1 (16)          892
Turniket AQTI 1 (20)           453
Zirzemi (arxa giris) (23)      363
Turniket AQTI 2 (21)           196
Name: point, dtype: int64

In [ ]:
indexes_appended = []
names_appended = []

for i in names:

  indexes = df[df['name'] == i]['point'].value_counts().index

  if len(indexes) > 1:

    indexes_appended.append(indexes)
    names_appended.append(i)

In [ ]:
len(names_appended)/len(names) # 71% of stuff uses more than one entrance

0.718562874251497

In [ ]:
df[
   (df['date'] == dates[0]) &
   (df['name'] == names[0])
]['direction'].value_counts()[0] == df[
   (df['date'] == dates[0]) &
   (df['name'] == names[0])
]['direction'].value_counts()[1]

True

In [ ]:
names_not_suitable = []

for date in dates:

  #for i in names:

  try:
    first_direction_count = df[
      (df['date'] == date) &
      (df['name'] ==  'Məmmədəliyev İlkin Adil')
    ]['direction'].value_counts()[0]
  except:
    first_direction_count = "ff"

  try:
    second_direction_count = df[
      (df['date'] == date) &
      (df['name'] ==  'Məmmədəliyev İlkin Adil')
    ]['direction'].value_counts()[1]
  except:
    second_direction_count = "ss"
  

  if first_direction_count != second_direction_count:
    print(f'{first_direction_count} {second_direction_count} {date}')

6 3 2021-12-01
5 2 2021-12-02
6 3 2021-12-03
ff ss 2021-12-04
ff ss 2021-12-05
6 2 2021-12-06
5 2 2021-12-07
4 1 2021-12-08
3 2 2021-12-09
5 1 2021-12-10
ff ss 2021-12-11
ff ss 2021-12-12
5 2 2021-12-13
6 3 2021-12-14
7 4 2021-12-15
ff ss 2021-12-18
ff ss 2021-12-19
5 3 2021-12-20
5 3 2021-12-21
6 2 2021-12-22
4 2 2021-12-23
7 4 2021-12-24
ff ss 2021-12-25
ff ss 2021-12-26
6 2 2021-12-27
11 4 2021-12-28
5 2 2021-12-29
6 2 2021-12-30
ff ss 2021-12-31

In [ ]:
df[
   (df['date'] == '2021-12-04') &
   (df['name'] == 'Sultanlı Saqibət Pərviz')
]

            date      time  ...                     name           date_time
2740  2021-12-04  15:11:23  ...  Sultanlı Saqibət Pərviz 2021-12-04 15:11:23

[1 rows x 7 columns]

In [ ]:
len(names_not_suitable)

121

In [ ]:
len(names)

334

In [ ]:
len(set(names_not_suitable))

334

In [ ]:
df['date_time'][0] - df['date_time'][100]

Timedelta('-1 days +21:00:02')

In [ ]:
sorted(names)

[' Bayramov Əflatun Şəmistan',
 'Abasova Nəzakət Mirsahib',
 'Abbasov Telman Məmməd',
 'Abbasova Güləndam ',
 'Abbasova Əfsanə',
 'Abdulla-zadə Mütəllim Fayiq',
 'Abdullayev Cavid',
 'Abdullayev Mirfazil Qafar',
 'Abdullayev Mirzə Mirfazil',
 'Abdullayeva Nigar Tohid',
 'Abdullayeva Saida Rəcəb',
 'Abdullayeva Sveta Tofiq',
 'Abdullayeva Yeganə Elman ',
 'Abışov Asəf',
 'Abışova Nuranə Elçin',
 'Allahverdiyev Fuad Qələndər',
 'Allahverdiyeva Arifə Nuşrəvan',
 'Alıyev Vahid Məhəmməd',
 'Alıyeva Aynurə Xalıqverdi',
 'Alıyeva Firəngiz Rəşad',
 'Alıyeva Günay İlyas',
 'Aslanlı İlqar',
 'Aslanov Rasim Rafiq',
 'Aslanov Səfa Şirin',
 'Aslanova Səfa Elman',
 'Avşarlı Fidan',
 'Axundova Ebru Nabil',
 'Axundova Nərmin ',
 'Axundova Südabə Həzi',
 'Ağalarova Nərmin Vaqif',
 'Ağayev Murad Vahid',
 'Ağayev Vüsal Şəfahət',
 'Ağayeva Nərgiz Cəmaləddin',
 'Ağazadə Elbəy Ağa',
 'Babakişiyeva Fidan Xamis',
 'Babayeva Nərmin Mənsim ',
 'Baxışov Samir Rəşadət',
 'Bayramov Cahangir Tofiq',
 'Bayramov Cəmil  Allahverən',
 'Bayramov Vüsal İlqar',
 'Bayramova Gülər Rövşən',
 'Bayramova Sevil Uveys',
 'Bayramzadə Emin Salman',
 'Bağırova Gültəkin Seymur',
 'Bağırova Mehriban Zabit',
 'Bədirli Günay Məqsəd ',
 'Bədəlova Fidan Elşad',
 'Bəylərova Aytən Hidayət',
 'Cabbarova Şükufə Hamil',
 'Cabbarova Əfsanə Nizami',
 'Camalova Zeynəb Əhməd',
 'Cəbrayılzadə Şəbnəm Zakir',
 'Cəfərova Gülay Güloğan',
 'Cəfərova Günel Səyad ',
 'Cəfərova Qərənfil Məmməd',
 'Cəfərzadə Mədinə',
 'Cəlilova Aysel Rövşən',
 'Cəlilova Ülviyyə Mahmud',
 'Cəlladov Qiyasəddin Şəfi',
 'Dadaşov Nicat Elmar ',
 'Doldolava Xədicə Murtuzəli',
 'Ellazova Sahibə Əli ',
 'Elxan Əsgərzadə',
 'Etibaroğlu Abdul Etibar',
 'Eyvazova Məhbubə Bakir',
 'Eyvazzadə Aytən Vaqif',
 'Fərəcova Nərmin Rəşid',
 'Gülgəzli Asya Bağı',
 'Güləhmədova Səadət Abdullayevna',
 'Hacıyev Fuad Allahverdi ',
 'Hacıyev Natiq Rzaqulu',
 'Hacıyeva Cəmilə Telman',
 'Hacıyeva Gülse',
 'Hacıyeva Nigar Üzeyir',
 'Hacıyeva Xəyalə Mətləb',
 'Hacızadə Cəmilə',
 'Hacızadə Şəbnəm İlqar',
 'Heydərova Sevinc Bağman',
 'Hilalova Rəna Vaqif',
 'Hümbətova Əminə Hüseyin',
 'Hünbətov Emil Eyvaz',
 'Hüseynli Həbib Şahin',
 'Hüseynov Hikmət Cəbrayıl',
 'Hüseynov Natiq Nahid',
 'Hüseynov Ziyabəddin Firudin',
 'Hüseynova Minəxanım Abdulla',
 'Hüseynova Mətanət Qaraş',
 'Hüseynova Sara Rizvan ',
 'Hüseynova Xatın Elman',
 'Hüseynova Xuraman Məmmədəli',
 'Hüseynova Ülviyyə Hafis',
 'Həsənli Rəvanə Mübariz',
 'Həsənli Tamilla Səlahəddin',
 'Həsənov Mirsamir Mir Asif',
 'Həsənov Səlim Rza',
 'Həsənova Aynur Elxan',
 'Həsənova Cəmilə Balağa',
 'Həsənova Elmira Fazil',
 'Həsənova Günel Pənah',
 'Həsənova Pərvanə Azad',
 'Həsənova Sona Allahverdi',
 'Həsənova Vəfa Səlim',
 'Həsənova Çinarə İlham',
 'Həsənzadə Qəribə Zaur',
 'Həşimov Həşim Eldar',
 'Həşimova Nigar Qorxmaz',
 'Kazımov Rahib Zinhar',
 'Kazımova Gövhər',
 'Kəngərli Rəna Surxay ',
 'Kərimli Elşən Aydın',
 'Kərimov Aydın Mikayıl',
 'Kərimova Elnarə Həmid',
 'Kərimova Ülviyyə',
 'Mahmudov Həsən Hüsən',
 'Mahmudova Mahirə Hacıağa',
 'Mehdiyev Faiq Cavanşir',
 'Mehdiyev Rəşadət Mehdi',
 'Mehdiyeva Mətanət',
 'Mirzəli Vüsalə İlyas',
 'Mirzəyeva Nigar Fəxrəddin',
 'Mirzəyeva Nuranə Cəbrayıl',
 'Mirzəzadə Nəzakət Qabil',
 'Mirzəzadə Səbinə Samir',
 'Misirli Misir Yusir',
 'Mollayeva Nuranə',
 'Muradova Dinar Murad',
 'Musayev Ruslan',
 'Musayev Tural Vüqar',
 'Musayev İlkin Xaqani',
 'Musayeva Ayla Osman',
 'Mustafayeva Fəridə Əyyub',
 'Mustafayeva Günəş Sarı',
 'Mustafayeva Kəmalə Vəkil',
 'Mustafayeva Nailə Xanbaba',
 'Mustafayeva Pərvin Təzəxan',
 'Mühafizə',
 'Mürsəlli Səmra Nizami',
 'Mürşüdova Bürhanə Qədəm',
 'Mürşüdova İradə İsbəndiyar',
 'Müsəvi Türkan Nizami',
 'Müzəffərova Afaq Mais',
 'Məhərrəmova Şeyda Məmməd',
 'Məlikova Ülkər Müslüm ',
 'Məmmədli Aynur',
 'Məmmədli Vüqar Ədalət',
 'Məmmədov Bayram Ənvər',
 'Məmmədov Natiq Mirzə',
 'Məmmədova Aysel Qasım',
 'Məmmədova Aysel Ərəstun ',
 'Məmmədova Aytən Elman',
 'Məmmədova Gülnarə Telman ',
 'Məmmədova Günəş Bəhram',
 'Məmmədova Mənsubə Şirin',
 'Məmmədova Nabat Fuad',
 'Məmmədova Ramilə Cəmaləddin',
 'Məmmədova Samirə Fikrət',
 'Məmmədova Samirə Qənbərəli',
 'Məmmədova Səbinə Cəbrayıl',
 'Məmmədova Şəbnəm Baba',
 'Məmmədova Əfsanə Oktay',
 'Məmmədzadə Məhsəti Nizami',
 'Məmmədzadə Rəşad Əli',
 'Məmmədəliyev İlkin Adil',
 'Mənsumova Xatirə İbrahim',
 'Namazova Gülnar Məcnun',
 'Namazova Şəhla Əlibala',
 'Nağıyeva Xəyalə Saleh',
 'Nağıyeva Əsmər Nazim',
 'Niyazova Elnara Saleh',
 'Nuraliyeva Nəzakət Şükür',
 'Nuralıyeva Samirə Mübariz',
 'Nuru-zadə Səbinə Canoğlan',
 'Nəbili Ləman Elşad',
 'Nəbiyev Nəbi Nuru',
 'Nəcəfov Abbasəli Akif',
 'Nəcəfova Rəhilə Allahverdi ',
 'Onişenko Leontiy Nikolayeviç',
 'Orucova Kəmalə Nobil',
 'Oruczadə Şəhriyar Qərib',
 'Orxan Mahir oğlu',
 'Paşazadə Toğrul',
 'Pirquliyeva Gülmirə Hacıbala',
 'Pirverdiyeva Aytən İsaq',
 'Poluxova Minayə Məhəmməd',
 'Qafarlı Nuray Azər',
 'Qafarov Seymur Məzahir (AGENTLİK)',
 'Qanbay Maqsud Murad',
 'Qaraxanlı Əliş Böyük',
 'Qasımlı Qasım ',
 'Qasımova Sahilə Zahid',
 'Qazıyeva Saida Seyfəddin',
 'Qocayeva Tünzalə Firdovsi ',
 'Quliyev Nihad Qüdrət',
 'Quliyev Vüqar Şirəli',
 'Quliyev İlqar Zülfüqar',
 'Quliyeva Aynurə Şahlar',
 'Quliyeva Könül Məhi',
 'Quliyeva Sona Elman',
 'Quliyeva İlhamə Rza',
 'Quluzadə Gülnarə Rövşən',
 'Qurbanov Natiq Cəlal (muzey)',
 'Qurbanova Röyalə Rəhim',
 'Qurbanova Səbinə Fehruz ',
 'Qüdrətli Aydan Rasim',
 'Qədimova Samirə Əli',
 'Qədirov Ramil Rafiq',
 'Qədirzadə Tural Murad',
 'Qəhrəmanova Gülnur',
 'Qənbərova Xalidə Vaqif',
 'Qəribli Türkan  Səbuhi',
 'Rzayev Sabir',
 'Rzayeva Jalə Məmmədağa',
 'Rzayeva Könül Nuru',
 'Rzayeva Xəyalə',
 'Rüstəmova Aysel Daşqın',
 'Rüstəmova Elvina Bayram',
 'Rüstəmzadə Səbinə Aydın',
 'Rəfiyeva Mələkxanım Azad',
 'Rəsulov Xəyal Ayaz',
 'Sadıqov Kənan İbrahim',
 'Sadıqova Arzu Əbil ',
 'Sadıqova Aytən Bəndalı',
 'Sadıqova Nüşabə Məhəmməd',
 'Sadıqova Nərmin',
 'Sadıqova Nərmin Rafiq',
 'Sadıqova İlahə Məhəmməd',
 'Sadıqzadə Həlimə Qaraş ',
 'Sadıxov İlham Balahüseyn',
 'Sairbəyli Nəzrin Ramiz',
 'Salah İnal Nofəl',
 'Salmanova Aydan Mətləb ',
 'Satiyev İlqar',
 'Seyfullayev Emil Məzahim',
 'Seyfullayev Samir Mübariz',
 'Seyidova Ləman Şirzad',
 'Seyidova Zeynəb',
 'Stanbullu Fəridə Dərgah',
 'Sultanlı Saqibət Pərviz',
 'Sultanova Sona Qalib',
 'Sulyayeva Elina',
 'Süleymanov Elman Məhəmməd',
 'Süleymanova Nəbahət Hidayət',
 'Səfərli Sərxan',
 'Səfərəliyeva Nərgiz İsmayıl',
 'Səlimov Aslan Yusif',
 'Səlimov Bəhram Kərim',
 'Səlimova Aysel',
 'Səlimova Lalə Yasər ',
 'Səlimova Sevinc',
 'Sərdarov Aqil Yaqub',
 'Tahirov Tural Şakir',
 'Talıbzadə Ədalət Yusif',
 'Tapdıqova Bəturə Ceyhun',
 'Tağıyeva Sitarə Sabir',
 'Verdiyeva Mehriban Fəxrəddin',
 'Vüqar Qurbanov Namaz',
 'Vəliyeva Aybəniz Alı',
 'Vətəni Mahirə Əhməd',
 'Xammədova Nuridə',
 'Xaydarov Azad Abidoviç ',
 'Xəlilova Səbinə Hakim',
 'Yusifli Əminə Afər',
 'Yusifli Əsmər Nəriman',
 'Yusifova Aynur Vidadi',
 'Yusifova Gülnarə Azadovna',
 'Zalov Zaur (Abşeron RSL)',
 'Zalova Gülnarə',
 'Zamanova Sevinc Nuhiddin',
 'Zeynalov Ruslan Hacıağa',
 'Zeynalova Pərvanə Əli',
 'Zeynalova Züleyxa Müşfiq',
 'Zərbalıyev Şiralı Mülkəsahib',
 'Çələbi Elşadə Nurəddin',
 'Çərkəsov Vüqar Əlif',
 'İbadov Elnur Adəm',
 'İbadov Faiq Adəm',
 'İbadova Mərziyyə Yadigar',
 'İbrahimova Mələkxanım İnqilab',
 'İsaqova Nərmin İlqar ',
 'İsayev Rövşən Barat',
 'İsayeva Reyhan Əli',
 'İsgəndərli Jalə Adil',
 'İsmayılov Yusif Elman',
 'İsmayılov İlqar Rafiq',
 'İsmayılova Xanım İbrahim',
 'İsrafilova Arzu',
 'İsrəfilov Dilqəm',
 'Şafahatzadə Fuad Əşrəf',
 'Şahvələdova Gülbəniz',
 'Şirinov Kənan Rasim',
 'Şirinova Xəyalə Elman',
 'Şükürlü Tural',
 'Şükürova Nəzakət',
 'Şəfiyev Şahin Tərlan',
 'Şərifli Kamran Mehman',
 'Əbilov Elyar Sultan',
 'Əfəndibəyov Emin Müşfiq ',
 'Əhmədov Ramin',
 'Əhmədova Cəmilə Ağamusa',
 'Əkbərova Rəna Nəsirulla',
 'Əliyev Arif Nail',
 'Əliyev Fərid İsgəndər',
 'Əliyev Teyyub Əlizahab',
 'Əliyev İlkin Zahid',
 'Əliyev Əliövsət Aydın',
 'Əliyeva Arzu Bakir ',
 'Əliyeva Fatimə Əhməd',
 'Əliyeva Gülnar Teyyub',
 'Əliyeva Kəmalə',
 'Əliyeva Nuridə',
 'Əliyeva Reyhan Şamil',
 'Əliyeva Roza Musa',
 'Əliyeva Rəna Şirəli',
 'Əliyeva Samirə Bəxtiyar',
 'Əliyeva Çiçək Vəli ',
 'Əliyeva Ülkər',
 'Əliyeva İlahə Mirsə-Əli',
 'Əliyeva Şahsənəm Kamandar',
 'Əliyeva Şəlalə Çingiz',
 'Əlizadə Fəxrəndə',
 'Əlizadə Selcan Azər',
 'Əlizadə İlkin Cəmil',
 'Ələkbərov Malik Mürsəl',
 'Ələkbərova Almaz Zakir ',
 'Ələsgərova Təhminə Sabir',
 'Əmirov Məcid',
 'Əsgərov Mehman Şahab',
 'Əsgərova Aynur Elxan ',
 'Əsədli Nəzrin Elşən',
 'Əzim Elmin Oktay',
 'Əzimov İlqar İlham',
 'Əzizli Ruslan',
 'Əzizli Yeganə',
 'Əzizov Orxan Vasif']

In [ ]:
df.sort_values(by=['date_time','name']).head(10)

         date      time  ...                      name           date_time
0  2021-12-01  06:07:55  ...    Məlikova Ülkər Müslüm  2021-12-01 06:07:55
1  2021-12-01  06:11:04  ...   Sadıqzadə Həlimə Qaraş  2021-12-01 06:11:04
2  2021-12-01  06:23:22  ...  Mahmudova Mahirə Hacıağa 2021-12-01 06:23:22
3  2021-12-01  06:23:25  ...  Həsənova Sona Allahverdi 2021-12-01 06:23:25
4  2021-12-01  06:23:28  ...     Zeynalova Pərvanə Əli 2021-12-01 06:23:28
5  2021-12-01  06:33:57  ...   Ələkbərova Almaz Zakir  2021-12-01 06:33:57
6  2021-12-01  06:36:07  ...   Ələkbərova Almaz Zakir  2021-12-01 06:36:07
7  2021-12-01  06:44:51  ...            Əliyeva Nuridə 2021-12-01 06:44:51
8  2021-12-01  06:56:16  ...       Əliyeva Rəna Şirəli 2021-12-01 06:56:16
9  2021-12-01  06:58:19  ...       Əliyeva Rəna Şirəli 2021-12-01 06:58:19

[10 rows x 7 columns]

In [ ]:
df.pivot_table(values='date_time', index=df.name, columns='direction', aggfunc='last').head(40)

direction                                   giriş              çıxış
name
 Bayramov Əflatun Şəmistan    2021-12-30 08:42:32 2021-12-30 17:44:14
Abasova Nəzakət Mirsahib      2021-12-30 11:02:05 2021-12-30 18:37:13
Abbasov Telman Məmməd         2021-12-10 09:24:23 2021-12-10 18:33:31
Abbasova Güləndam             2021-12-30 08:41:49 2021-12-30 18:17:56
Abbasova Əfsanə               2021-12-30 14:55:05 2021-12-30 16:36:23
Abdulla-zadə Mütəllim Fayiq   2021-12-30 16:02:46 2021-12-30 17:35:32
Abdullayev Cavid              2021-12-28 09:16:16 2021-12-28 17:50:17
Abdullayev Mirfazil Qafar     2021-12-30 14:55:53 2021-12-30 18:01:12
Abdullayev Mirzə Mirfazil     2021-12-29 17:02:11 2021-12-29 17:48:00
Abdullayeva Nigar Tohid       2021-12-30 14:23:45 2021-12-30 15:19:31
Abdullayeva Saida Rəcəb       2021-12-30 14:52:08 2021-12-30 17:11:07
Abdullayeva Sveta Tofiq       2021-12-30 09:11:36 2021-12-30 17:37:09
Abdullayeva Yeganə Elman      2021-12-30 09:35:54 2021-12-30 17:30:37
Abışov Asəf                   2021-12-17 12:20:26 2021-12-17 17:31:46
Abışova Nuranə Elçin          2021-12-30 08:34:41 2021-12-30 17:55:27
Allahverdiyev Fuad Qələndər   2021-12-30 09:22:48 2021-12-30 17:28:20
Allahverdiyeva Arifə Nuşrəvan 2021-12-30 09:08:49 2021-12-30 16:31:51
Alıyev Vahid Məhəmməd         2021-12-30 09:32:29 2021-12-30 15:38:11
Alıyeva Aynurə Xalıqverdi     2021-12-30 14:54:59 2021-12-30 18:06:56
Alıyeva Firəngiz Rəşad        2021-12-28 09:41:57 2021-12-28 10:45:35
Alıyeva Günay İlyas           2021-12-30 09:37:05 2021-12-30 17:44:10
Aslanlı İlqar                 2021-12-29 12:49:38 2021-12-29 15:11:52
Aslanov Rasim Rafiq           2021-12-30 17:14:40 2021-12-30 17:20:29
Aslanov Səfa Şirin            2021-12-29 09:45:25 2021-12-28 18:31:01
Aslanova Səfa Elman           2021-12-29 09:39:48 2021-12-29 18:33:27
Avşarlı Fidan                 2021-12-30 09:24:20 2021-12-30 17:03:24
Axundova Ebru Nabil           2021-12-30 13:51:35 2021-12-30 18:32:34
Axundova Nərmin               2021-12-30 16:02:31 2021-12-30 13:13:28
Axundova Südabə Həzi          2021-12-29 09:06:08 2021-12-29 17:30:22
Ağalarova Nərmin Vaqif        2021-12-30 16:02:08 2021-12-30 17:19:34
Ağayev Murad Vahid            2021-12-16 15:39:51 2021-12-14 11:12:41
Ağayev Vüsal Şəfahət          2021-12-27 16:29:37 2021-12-27 19:22:11
Ağayeva Nərgiz Cəmaləddin     2021-12-29 13:37:56 2021-12-29 17:32:38
Ağazadə Elbəy Ağa             2021-12-30 16:42:23 2021-12-30 17:41:20
Babakişiyeva Fidan Xamis      2021-12-30 14:12:59 2021-12-30 15:28:25
Babayeva Nərmin Mənsim        2021-12-29 09:35:54 2021-12-29 12:49:46
Baxışov Samir Rəşadət         2021-12-10 12:47:08                 NaT
Bayramov Cahangir Tofiq       2021-12-31 13:17:25 2021-12-31 13:25:04
Bayramov Cəmil  Allahverən    2021-12-30 09:30:16 2021-12-30 18:45:11
Bayramov Vüsal İlqar          2021-12-30 13:23:50 2021-12-30 17:55:30

In [ ]:
df.pivot_table(values='date_time', index=df.name, columns='direction', aggfunc='all').head(40)

direction                     giriş çıxış
name
 Bayramov Əflatun Şəmistan     True   True
Abasova Nəzakət Mirsahib       True   True
Abbasov Telman Məmməd          True   True
Abbasova Güləndam              True   True
Abbasova Əfsanə                True   True
Abdulla-zadə Mütəllim Fayiq    True   True
Abdullayev Cavid               True   True
Abdullayev Mirfazil Qafar      True   True
Abdullayev Mirzə Mirfazil      True   True
Abdullayeva Nigar Tohid        True   True
Abdullayeva Saida Rəcəb        True   True
Abdullayeva Sveta Tofiq        True   True
Abdullayeva Yeganə Elman       True   True
Abışov Asəf                    True   True
Abışova Nuranə Elçin           True   True
Allahverdiyev Fuad Qələndər    True   True
Allahverdiyeva Arifə Nuşrəvan  True   True
Alıyev Vahid Məhəmməd          True   True
Alıyeva Aynurə Xalıqverdi      True   True
Alıyeva Firəngiz Rəşad         True   True
Alıyeva Günay İlyas            True   True
Aslanlı İlqar                  True   True
Aslanov Rasim Rafiq            True   True
Aslanov Səfa Şirin             True   True
Aslanova Səfa Elman            True   True
Avşarlı Fidan                  True   True
Axundova Ebru Nabil            True   True
Axundova Nərmin                True   True
Axundova Südabə Həzi           True   True
Ağalarova Nərmin Vaqif         True   True
Ağayev Murad Vahid             True   True
Ağayev Vüsal Şəfahət           True   True
Ağayeva Nərgiz Cəmaləddin      True   True
Ağazadə Elbəy Ağa              True   True
Babakişiyeva Fidan Xamis       True   True
Babayeva Nərmin Mənsim         True   True
Baxışov Samir Rəşadət          True    NaN
Bayramov Cahangir Tofiq        True   True
Bayramov Cəmil  Allahverən     True   True
Bayramov Vüsal İlqar           True   True

In [ ]:
#df.pivot(index=df['name'], columns='direction')['date_time']